---
.gitignore:
  paths:
    - .rake_tasks
    - .rvmrc
    - /modules/
    - /spec/fixtures/modules/foreman_hammer
    - /keys
    - /examples/inventory.yaml
    - /examples/inventory.yaml.2*

.pdkignore:
  paths:
    - /scripts/
    - .rake_tasks
    - Puppetfile
".travis.yml":
  #global_env:
  deploy_to_forge:
    enabled: false
  branches:
    - release
  use_litmus: true
  litmus:
    provision_list:
      - travis_deb
      - travis_ub
      - travis_el7
      - travis_el8
      - ---travis_el
  simplecov: true