---
.gitignore:
  paths:
    - .rake_tasks
    - .rvmrc
    - /modules/
    - /spec/fixtures/modules/foreman_hammer
    - /keys

.pdkignore:
  paths:
    - /scripts/
    - .rake_tasks
    - Puppetfile